version: "3"
service:
apmriopreto:
  build: ./
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - .:/var/www/html
  links: 
    - db
db:
  image: mysql:5.7

  volumes:
   - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: apmriopreto
    MYSQL_USER: apmriopreto
    MYSQL_PASSWORD: 123456
phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
    
